# Generated by Django 5.2.4 on 2025-08-01 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255, verbose_name='Offer Name')),
                ('need_approval', models.BooleanField(default=True, verbose_name='Needs Approval')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('countries', models.JSONField(default=list, help_text='Select countries where this offer is available', verbose_name='Target Countries')),
                ('devices', models.JSONField(default=list, help_text='Select devices supported by this offer', verbose_name='Supported Devices')),
                ('payout', models.DecimalField(decimal_places=2, help_text='Commission payout in USD', max_digits=10, verbose_name='Payout (USD)')),
                ('epc', models.DecimalField(blank=True, decimal_places=2, help_text='Earnings Per Click in USD', max_digits=10, null=True, verbose_name='EPC (USD)')),
                ('note', models.TextField(blank=True, help_text='Additional notes about this offer', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
