# Generated by Django 5.2.4 on 2025-08-01 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Response Date')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin Note')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer', verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Offer Request',
                'verbose_name_plural': 'User Offer Requests',
                'ordering': ['-request_date'],
                'unique_together': {('user', 'offer')},
            },
        ),
    ]
