# Generated by Django 5.2.4 on 2025-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_userofferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_url',
            field=models.URLField(default='https://www.demourl.com', help_text='URL from the third-party CPA network', max_length=500, verbose_name='Original Offer URL'),
        ),
    ]
