# Generated by Django 5.2.4 on 2025-08-02 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_offer_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Click Date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Visitor IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Referrer')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visitor Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visitor City')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer', verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Affiliate User')),
            ],
            options={
                'verbose_name': 'Click Tracking',
                'verbose_name_plural': 'Click Tracking',
                'ordering': ['-click_date'],
                'indexes': [models.Index(fields=['user', 'offer'], name='offers_clic_user_id_562944_idx'), models.Index(fields=['click_date'], name='offers_clic_click_d_98a733_idx'), models.Index(fields=['ip_address'], name='offers_clic_ip_addr_44de9a_idx')],
            },
        ),
    ]
