# Generated by Django 5.2.4 on 2025-08-02 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_clicktracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Conversion Date')),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payout (USD)')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('network_click_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Network Click ID')),
                ('network_payout', models.CharField(blank=True, max_length=100, null=True, verbose_name='Network Payout')),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'ordering': ['-conversion_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CPA Network', max_length=255, verbose_name='Site Name')),
                ('domain_name', models.CharField(default='yourdomain.com', help_text='Your domain name without http/https (e.g., yourdomain.com)', max_length=255, verbose_name='Domain Name')),
                ('site_url', models.URLField(default='https://yourdomain.com', help_text='Full site URL with protocol (e.g., https://yourdomain.com)', max_length=500, verbose_name='Site URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='click_id',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='Click ID'),
        ),
        migrations.AddField(
            model_name='offer',
            name='cpa_network',
            field=models.CharField(blank=True, help_text='Select the CPA network for this offer', max_length=100, null=True, verbose_name='CPA Network'),
        ),
        migrations.AddIndex(
            model_name='clicktracking',
            index=models.Index(fields=['click_id'], name='offers_clic_click_i_bae224_idx'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='click_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.clicktracking', verbose_name='Click Tracking'),
        ),
    ]
