# Generated by Django 5.2.4 on 2025-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_conversion_sitesettings_clicktracking_click_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cpa_network',
            field=models.CharField(help_text='Select the CPA network for this offer', max_length=100, verbose_name='CPA Network'),
        ),
    ]
