# Generated by Django 5.2.4 on 2025-08-02 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offer_cpa_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPANetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_key', models.CharField(help_text="Unique identifier for the network (e.g., 'NexusSyner')", max_length=100, unique=True, verbose_name='Network Key')),
                ('name', models.CharField(help_text='Display name of the CPA network', max_length=255, verbose_name='Network Name')),
                ('description', models.TextField(help_text='Description of the network', verbose_name='Description')),
                ('click_id_parameter', models.CharField(help_text="Parameter name for sending click ID (e.g., 's2', 'subid')", max_length=100, verbose_name='Click ID Parameter')),
                ('postback_click_id_parameter', models.CharField(help_text='Parameter name for receiving click ID in postback', max_length=100, verbose_name='Postback Click ID Parameter')),
                ('postback_payout_parameter', models.CharField(help_text='Parameter name for receiving payout in postback', max_length=100, verbose_name='Postback Payout Parameter')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this network is active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'CPA Network',
                'verbose_name_plural': 'CPA Networks',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='clicktracking',
            name='click_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Click ID'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cpa_network',
            field=models.ForeignKey(help_text='Select the CPA network for this offer', on_delete=django.db.models.deletion.CASCADE, to='offers.cpanetwork', verbose_name='CPA Network'),
        ),
    ]
