# Generated by Django 5.2.4 on 2025-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_cpanetwork_alter_clicktracking_click_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_description',
            field=models.TextField(blank=True, help_text='Detailed description of the offer', null=True, verbose_name='Offer Description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_image',
            field=models.ImageField(blank=True, help_text='Image for the offer (optional)', null=True, upload_to='offers/', verbose_name='Offer Image'),
        ),
    ]
