# Generated by Django 5.2.4 on 2025-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offer_offer_description_offer_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktracking',
            name='subid1',
            field=models.CharField(blank=True, help_text='Optional subid parameter 1', max_length=100, null=True, verbose_name='Subid 1'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='subid2',
            field=models.CharField(blank=True, help_text='Optional subid parameter 2', max_length=100, null=True, verbose_name='Subid 2'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='subid3',
            field=models.CharField(blank=True, help_text='Optional subid parameter 3', max_length=100, null=True, verbose_name='Subid 3'),
        ),
    ] 