# Generated by Django 5.2.4 on 2025-08-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_add_subid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktracking',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visitor Region'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visitor Timezone'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Visitor Postal Code'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Visitor Organization'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ] 