# Generated by Django 5.2.4 on 2025-08-06 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_add_ip_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Manager Name')),
                ('picture', models.ImageField(help_text="Manager's profile picture", upload_to='managers/', verbose_name='Profile Picture')),
                ('whatsapp', models.CharField(help_text='WhatsApp number with country code (e.g., +1234567890)', max_length=20, verbose_name='WhatsApp Number')),
                ('email', models.EmailField(help_text="Manager's email address", max_length=254, verbose_name='Email Address')),
                ('telegram', models.CharField(help_text='Telegram username (without @)', max_length=100, verbose_name='Telegram Username')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this manager is active and available for assignment', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'ordering': ['name'],
            },
        ),
    ]
