# Generated by Django 5.2.4 on 2025-08-08 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Mark this conversion as rejected by admin', verbose_name='Is Rejected'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected this conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_conversions', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting this conversion', null=True, verbose_name='Rejection Reason'),
        ),
    ]
