# Generated by Django 5.2.4 on 2025-08-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_conversion_is_rejected_conversion_rejected_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20, verbose_name='Status'),
        ),
    ]
