# Generated by Django 5.2.4 on 2025-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='referral_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage of commission to give to referrers (e.g., 5.00 for 5%)', max_digits=5, verbose_name='Referral Percentage'),
        ),
    ]
