# Generated by Django 5.2.4 on 2025-08-08 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_sitesettings_referral_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, unique=True, verbose_name='Referral Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL, verbose_name='Referrer')),
            ],
            options={
                'verbose_name': 'Referral Link',
                'verbose_name_plural': 'Referral Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_at', models.DateTimeField(auto_now_add=True, verbose_name='Referred At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='Referred User')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL, verbose_name='Referrer')),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='offers.referrallink', verbose_name='Referral Link')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-referred_at'],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Earning Amount')),
                ('percentage_used', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to='offers.conversion', verbose_name='Conversion')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to='offers.referral', verbose_name='Referral')),
            ],
            options={
                'verbose_name': 'Referral Earning',
                'verbose_name_plural': 'Referral Earnings',
                'ordering': ['-created_at'],
                'unique_together': {('referral', 'conversion')},
            },
        ),
    ]
