# Generated by Django 5.2.4 on 2025-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_referrallink_referral_referralearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Noticeboard',
                'ordering': ['-created_at'],
            },
        ),
    ]
