# Generated by Django 5.2.4 on 2025-08-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_noticeboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='title',
        ),
    ]
