# Generated by Django 5.2.4 on 2025-08-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpanetwork',
            name='postback_payout_parameter',
        ),
    ]
