# Generated by Django 5.2.4 on 2025-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_remove_cpanetwork_postback_payout_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpanetwork',
            name='click_id_wrapper',
            field=models.CharField(default='{}', help_text='Wrapper characters around click ID (e.g., {} for {s2}, # for #s2#, [] for [s2])', max_length=10, verbose_name='Click ID Wrapper'),
        ),
    ]
