"""
Django settings for cpa project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8c$)6@&4x8nvp6hxf*7^ii7z4ny6k39ojpk8x6hlpmj=0ba8%q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'user',
    'offers',
    'django_crontab',  # Add django-crontab for scheduled tasks
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'offers.middleware.ReferralTrackingMiddleware',  # Add referral tracking middleware
]

ROOT_URLCONF = 'cpa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'offers.context_processors.notification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cpa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'staticfiles']
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

# Tracking domains for affiliate links
TRACKING_DOMAINS = [
    'http://localhost:8000',
    'https://track1.yourdomain.com',
    'https://track2.yourdomain.com',
    'https://track3.yourdomain.com',
    'https://track4.yourdomain.com',
    'https://track5.yourdomain.com',
]

# Default tracking domain
DEFAULT_TRACKING_DOMAIN = 'http://localhost:8000'

# Django Crontab Configuration
# ============================

# CRONJOBS - List of scheduled jobs
# Format: (cron_timing, python_module_path, [args], {kwargs}, suffix)
# Cron timing format: minute hour day month weekday
# Examples:
# '0 6 * * *' - Every day at 6:00 AM
# '0 6 * * 1' - Every Monday at 6:00 AM
# '0 6 1 * *' - First day of every month at 6:00 AM

CRONJOBS = [
    # Run payment processing every day at 6:00 AM
    ('0 6 * * *', 'django.core.management.call_command', ['process_payments'], {}, '>> /var/log/cpa_cron.log 2>&1'),
]

# CRONTAB_LOCK_JOBS - Prevent overlapping jobs
# Set to True to prevent starting a job if an old instance is still running
CRONTAB_LOCK_JOBS = True

# CRONTAB_COMMAND_PREFIX - Environment variables or commands to run before each job
# Example: 'STAGE=production'
CRONTAB_COMMAND_PREFIX = ''

# CRONTAB_COMMAND_SUFFIX - Commands to run after each job
# Example: '2>&1' for error redirection
CRONTAB_COMMAND_SUFFIX = ''

# CRONTAB_COMMENT - Comment to mark crontab entries for this project
CRONTAB_COMMENT = 'django-crontabs for cpa'

# CRONTAB_EXECUTABLE - Path to crontab executable
# Default: '/usr/bin/crontab'
CRONTAB_EXECUTABLE = '/usr/bin/crontab'

# CRONTAB_PYTHON_EXECUTABLE - Path to Python interpreter
# Default: Uses the interpreter used to add jobs
CRONTAB_PYTHON_EXECUTABLE = '/usr/bin/python3'

# CRONTAB_DJANGO_MANAGE_PATH - Path to manage.py file
# Default: Built using DJANGO_PROJECT_NAME
CRONTAB_DJANGO_MANAGE_PATH = str(BASE_DIR / 'manage.py')

# CRONTAB_DJANGO_SETTINGS_MODULE - Django settings module
# Default: From environment variable
CRONTAB_DJANGO_SETTINGS_MODULE = 'cpa.settings'
