# Generated by Django 5.2.4 on 2025-08-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_manager'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.manager', verbose_name='Assigned Manager'),
        ),
    ]
