# Generated by Django 5.2.4 on 2025-08-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="User's current balance in USD", max_digits=10, verbose_name='Balance'),
        ),
    ]
