# Generated by Django 5.2.4 on 2025-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conversion_counter',
            field=models.PositiveIntegerField(default=0, help_text='Total number of conversion attempts (including filtered ones)', verbose_name='Conversion Counter'),
        ),
    ]
