# Generated by Django 5.2.4 on 2025-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_conversion_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activated'),
        ),
    ]
