# Generated by Django 5.2.4 on 2025-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_last_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_is_active',
            field=models.BooleanField(default=True, help_text='Used by cronjob to track activation status changes', verbose_name='Previous Activation Status'),
        ),
    ]
